var config = {
	serverUrl:"http://139.196.13.206:3000",
	dbUrl:"mongodb://139.196.13.206/shopmall",
	success:{
		code:"200",
		message:"ok"
	},
	lack:{
		code:"400",
		message:"缺少参数"
	},
	loginTimeOut:{
		code:"80001",
		message:"登录超时"
	},
	error:{
		code:"80002",
		message:"操作错误"
	},
	index:{
		title:"主页"
	},
	productCenter:{
		title:"产品中心"
	},
	download:{
		title:"文档下载"
	},
	support:{
		title:"技术支持"
	},
	contact:{
		title:'联系我们'
	},
	about:{
		title:'关于我们'
	},
	shop:{
		title:"在线商城"
	},
	list:[
		{
			name:"测试数据产品文档一"
		},
		{
			name:"测试数据产品文档二"
		},
		{
			name:"测试数据产品文档三"
		},
		{
			name:"测试数据产品文档四"
		}
	],
	data:{
		success:{
			code:"200",
			message:"ok"
		},
		error:{
			code:"500",
			message:"server is error"
		},
		missParameter:{
			code:"400",
			message:"miss parameter"
		},
		notFound:{
			code:"404",
			message:"get data is null"
		},
		notPass:{
			code:"80001",
			message:"原始密码错误"
		},
		hasExit:{
			code:"80001",
			message:"您添加的分类已存在,请重新添加"
		},
		notClassId:{
			code:"80001",
			message:"更新失败,服务器繁忙"
		},
		notFindDeleteObj:{
			code:"80001",
			message:"删除失败,无此记录"
		},
		notCreat:{
			code:"80001",
			message:"添加失败,该分类已存在!"
		}
	},
	path:"public/images/upload/",
	downloadPath:'public/download/',
	productPath:'public/images/product/',
	uploadUrl:"http://139.196.13.206/shop/public/images/upload",
	productUrl:"http://139.196.13.206/shop/public/images/product",
	downloadPathUrl:'http://139.196.13.206/shop/public/download',
	delUploadPath:"./public/images/upload/",
};
module.exports = config;